[2023-09-21T14:31:10.394+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_dag.training scheduled__2023-09-18T00:00:00+00:00 [queued]>
[2023-09-21T14:31:10.402+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_dag.training scheduled__2023-09-18T00:00:00+00:00 [queued]>
[2023-09-21T14:31:10.403+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T14:31:10.414+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): training> on 2023-09-18 00:00:00+00:00
[2023-09-21T14:31:10.423+0000] {standard_task_runner.py:57} INFO - Started process 1499 to run task
[2023-09-21T14:31:10.430+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'training_dag', 'training', 'scheduled__2023-09-18T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmptu8o0azk']
[2023-09-21T14:31:10.434+0000] {standard_task_runner.py:85} INFO - Job 198: Subtask training
[2023-09-21T14:31:10.493+0000] {task_command.py:415} INFO - Running <TaskInstance: training_dag.training scheduled__2023-09-18T00:00:00+00:00 [running]> on host 44511c2b2f88
[2023-09-21T14:31:10.577+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='training_dag' AIRFLOW_CTX_TASK_ID='training' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-18T00:00:00+00:00'
[2023-09-21T14:31:12.402+0000] {logging_mixin.py:151} INFO - Cross validation results: {'fit_time': array([0.19507623, 0.07909632, 0.05868959, 0.10594368, 1.16330242]), 'score_time': array([0.00585222, 0.00488806, 0.00379777, 0.00431442, 0.01388097]), 'test_neg_mean_squared_error': array([-1.09288858e+11, -3.90783758e+10, -1.02029245e+10, -5.02066167e+09,
       -2.44195070e+10]), 'train_neg_mean_squared_error': array([-0.00321452, -0.00687988, -0.00835205, -0.01094971, -0.00898437]), 'test_r2': array([0.60300368, 0.61525092, 0.1594864 , 0.75184415, 0.50844342]), 'train_r2': array([1., 1., 1., 1., 1.])}
[2023-09-21T14:31:13.531+0000] {logging_mixin.py:151} INFO - Mean accuracy score: 0.53+/-0.20
[2023-09-21T14:31:13.534+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/training/training.py", line 76, in train_eval_save_model
    joblib.dump(model, model_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/model.pkl'
[2023-09-21T14:31:13.556+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=training_dag, task_id=training, execution_date=20230918T000000, start_date=20230921T143110, end_date=20230921T143113
[2023-09-21T14:31:13.571+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 198 for task training ([Errno 2] No such file or directory: '/opt/airflow/models/model.pkl'; 1499)
[2023-09-21T14:31:13.599+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T14:31:13.626+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
