[2023-09-21T13:51:41.726+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:37.848991+00:00 [queued]>
[2023-09-21T13:51:41.737+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:37.848991+00:00 [queued]>
[2023-09-21T13:51:41.738+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T13:51:41.752+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonSensor): wait_for_csv> on 2023-09-21 13:50:37.848991+00:00
[2023-09-21T13:51:41.762+0000] {standard_task_runner.py:57} INFO - Started process 16157 to run task
[2023-09-21T13:51:41.775+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cleaning_dag', 'wait_for_csv', 'manual__2023-09-21T13:50:37.848991+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/cleaning_dag.py', '--cfg-path', '/tmp/tmp9_nueq3q']
[2023-09-21T13:51:41.783+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask wait_for_csv
[2023-09-21T13:51:41.899+0000] {task_command.py:415} INFO - Running <TaskInstance: cleaning_dag.wait_for_csv manual__2023-09-21T13:50:37.848991+00:00 [running]> on host c14470e00ccc
[2023-09-21T13:51:42.062+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felicien' AIRFLOW_CTX_DAG_ID='cleaning_dag' AIRFLOW_CTX_TASK_ID='wait_for_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T13:50:37.848991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T13:50:37.848991+00:00'
[2023-09-21T13:51:42.065+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac2e50>
[2023-09-21T13:52:42.115+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac2e50>
[2023-09-21T13:53:42.162+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac2e50>
[2023-09-21T13:54:42.256+0000] {python.py:72} INFO - Poking callable: <function check_csv_exists at 0xffff87ac2e50>
[2023-09-21T13:55:36.173+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-09-21T13:55:36.187+0000] {process_utils.py:131} INFO - Sending 15 to group 16157. PIDs of all processes in the group: [16157]
[2023-09-21T13:55:36.188+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 16157
[2023-09-21T13:55:36.191+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-21T13:55:36.284+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=16157, status='terminated', exitcode=0, started='13:51:41') (16157) terminated with exit code 0
